### ISSUE TITLE
Armor stands logged without player name

### ISSUE THREAD

**Issue by Absentee23** [AddstarMC/Prism-Bukkit#1]
I've noticed that it logs armor stand placement, but as "**default** spawned armor_stand" (instead of the player name).

**Comment by michalet** [comment]
For armor stands, I'd add that destroying them's not logged at all, at least not when I tried.

**Comment by addstar** [comment]
I will be working on this soon (hopefully)..

**Comment by kangarko** [comment]
@addstar  they added an armorstandevent (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/0f0e31b86bec91e2c1d5d4186e722c863b6b644c)
it can help with the issue

**Comment by addstar** [comment]
@kangarko, thanks I'll look into this when I start working on it. I've been pretty busy lately and haven't had much time.
