### ISSUE TITLE
Remove the pasteAPI

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#114]
I am not sure this api is even functional anymore and if anyone uses it -  

Additionally it presents issues if and when some moves to java 11.  It requires additional dependencies in that environment - 

I would appreciate community feedback

**Comment by addstar** [comment]
Not that giving my opinion makes much difference, for obvious reasons.. but I'd like to test this to see if it even works. if not, I think it can just be removed.

But if it does still work, I'd also like to hear from the community. Maybe some don't currently use it but would like to? Feedback wanted! :)

**Comment by viveleroi** [comment]
It can be completely dumped. I recently let the pste.me domain expire with the intent of shutting the service down, but it's API hasn't been functional in years (and was never really used). I love the idea of this feature, but as-written it's useless.

**Comment by Narimm** [comment]
Well that answers that - that being said I have actually worked directly with the PASTEBIN api and it works in a really similar fashion howver I think it allows a JSON submission v XML which is sort of ideal

**Comment by Narimm** [comment]
We will move to past.gg
