### ISSUE TITLE
Add custom Metrics Charts

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#127]
With metrics now supporting customized views - we need to discuss what metrics Prism should report on.

**Comment by addstar** [comment]
> You realize you could have done this with bStats 1.4, right?

Yes, but not sure the relevance. We weren't waiting for 1.7 specifically, we just wanted the Prism/bstats issues resolved before looking into this.

> Anyway, log the database server software and version as a combined string. e.g., "MySQL_5.7.29"

Good suggestion :+1: I definitely want this also.

**Comment by Bobcat00** [comment]
Oh, how could I forget:  useNonStandardSql true/false.

**Comment by Narimm** [comment]
I am not sure the nonstandard sql thing is important anymore because its automatic now sort of

**Comment by Narimm** [comment]
This is not really required
