### ISSUE TITLE
[Bug] Editing other player's inventories causes NPE

### ISSUE THREAD

**Issue by Draycia** [AddstarMC/Prism-Bukkit#132]
Issue:
Using essentialsx's `/invsee` or openinv's `/openinv` to edit another player's inventory results in one of two different NPEs being thrown.

Errors:
https://pastebin.com/nk20jkaQ
https://pastebin.com/9uS4GxRu

Plugins:
`Plugins (2): Essentials, Prism`

Server:
```
[00:35:53 INFO]: This server is running Paper version git-Paper-135 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[00:35:53 INFO]: Checking version, please wait...
[00:35:54 INFO]: Previous version: git-Purpur-489 (MC: 1.15.2)
[00:35:54 INFO]: You are running the latest version
```

Tested on java-13 and java-14.

Config is completely unchanged except for necessary MySQL settings.

**Comment by Draycia** [comment]
Also, this primarily happens when placing items into the target's inventory, though I believe I have seen an NPE when picking up items.

Nothing is thrown when editing my own inventory whilst in `/invsee` however.

**Comment by Bobcat00** [comment]
Me too.  This wasn't from /invsee, this was apparently a player accessing his enderchest.

https://pastebin.com/FNWpzrPu
