### ISSUE TITLE
Remove block_subid - clear up queries remove IntPair()

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#133]
Block sub id is redundant - its no longer used as we use BlockState

However because block state quering is very very slow as it is doing a string match we may need to consider converting the state to an more easily queriable storage system

**Comment by addstar** [comment]
Needs more discussion - I'm dubious about the performance impact of this redundant field, but I may misunderstand how it's used in queries. Every `block_subid` now is always `0` and I'm not aware of why this will impact performance.

Please link to specific code lines that are of concern or are candidates for possible performance improvements.

**Comment by Narimm** [comment]
Closed as No relevant
