### ISSUE TITLE
unable to load driver

### ISSUE THREAD

**Issue by PhanaticD** [AddstarMC/Prism-Bukkit#138]
https://pastebin.com/raw/fA0Fyyht

I had this similar issue with another plugin I think it has to do with not relocating hikaricp

**Comment by PhanaticD** [comment]
I tried relocating com.zaxxer in shade and it didnt change anything

**Comment by Narimm** [comment]
Relocating Hikari doesn't affect the driver itself - the driver is supplied by your underlying server instance.   Given this bug isn't affecting the other 100's of servers at this stage this is on hold until we see verifications.  I am not saying relocating Hikari isn't a good idea - just that I doubt it fixes a missing SQL driver.

**Comment by PhanaticD** [comment]
I am not sure what is wrong with my server then, I was just using the latest paper as of this post right off their website

**Comment by PhanaticD** [comment]
could it be due to using mariadb?

**Comment by PhanaticD** [comment]
this only occurs with https://dev.bukkit.org/projects/gringotts installed, so it appears to be due to that plugin somehow (i have a server where I have a ton of plugins enabled for update testing)
