### ISSUE TITLE
Armor Stands (1.9)

### ISSUE THREAD

**Issue by BiGUNMAN** [AddstarMC/Prism-Bukkit#15]
Hi, I was wondering whether or not this would ever be updated to support armor stands/other 1.9/1.10 things?

**Comment by addstar** [comment]
Hello, yes armor stands are already supported, although I don't remember if they fully restore the items they had on them. Also, as we use this plugin heavily, it will continue to be updated. But we also don't have a lot of time and have many other plugins we maintain, so it might not be quick.
Feel free to submit PRs if you have any improvements you'd like to make 😃
