### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Prism-Bukkit#17]
Hi, since I've upgraded to 1.11.2, Im having those errors now and I'm not sure if they're harmless...

18:38:57 Prism]:: Database connection error: Incorrect string value: '\xF0\x9F\xA6\x84' for column 'data' at row 1
18:38:57 CONSOLE: WARN]: java.sql.BatchUpdateException: Incorrect string value: '\xF0\x9F\xA6\x84' for column 'data' at row 1
18:38:57 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
18:38:57 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
18:38:57 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
18:38:57 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:387)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
18:38:57 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertExtraData(RecordingTask.java:321)
18:38:57 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:255)
18:38:57 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:35)
18:38:57 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:351)
18:38:57 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
18:38:57 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
18:38:57 CONSOLE: WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
18:38:57 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:38:57 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:38:57 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
18:38:57 CONSOLE: WARN]: Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\xA6\x84' for column 'data' at row 1
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
18:38:57 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
18:38:57 CONSOLE: WARN]: ... 12 more

Prism build #16 from your CI

**Comment by Narimm** [comment]
Closing as no longer recent
