### ISSUE TITLE
[BUG] Torches, Bells, Redstone Torches not logged via causality

### ISSUE THREAD

**Issue by RanrMC** [AddstarMC/Prism-Bukkit#172]
**Describe the bug**
Torches placed on walls are not logged unless they're placed on top of the block. Torches & redstone torches placed on the sides of blocks are not logged when the block they are attached to is broken.

Bells do not appear to have any causal logs. If the block they are attached to is broken, they are not logged.

**To Reproduce**
Place a torch on the side of a block then break the block it is attached to which will cause the torch to fall. Enable inspector wand and click where the torch used to be and you will find no logs.

Place Bell on a block and break the block it is attached to and inspect with wand. No logs are found.
**Server (please complete the following information):**
  - Prism Version: 2.1.6-127
  - Server Type: Spigot
  - Server Version: 1.15.2

**Comment by Orlaando-dev** [comment]
I was able to re-produce this on build 144.
