### ISSUE TITLE
[BUG] Writable Books Contents & Paintings Not Rolled Back

### ISSUE THREAD

**Issue by RanrMC** [AddstarMC/Prism-Bukkit#174]
**Describe the bug**
When rolling back a writable book, the item itself comes back but not the contents written inside. Paintings do not rollback when attempted, and are not logged when destroyed via tnt.

**To Reproduce**
Destroy/remove a writable book (unsigned) then roll it back.

Place painting and have it destroyed. Attempt to roll it back, it will claim it has succeeded but the painting will not return.

**Expected behavior**
Expected book to return with its contents.

Expected painting to return.

**Screenshots**
N/A

**Server (please complete the following information):**
  - Prism Version: 2.1.6
  - Server Type: Spigot
  - Server Version: 1.15.2

**Additional context**

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
