### ISSUE TITLE
PlayerJoinEvent could be optimised

### ISSUE THREAD

**Issue by I-Knight-I** [AddstarMC/Prism-Bukkit#180]
- Prism 2.1.6
- Paper 103
- Minecraft 1.15.2
- R5 3600 + 8GB RAM

As it currently stands, the PlayerJoinEvent in Prism is the 2nd biggest contributor to tick usage (when testing joining performance). The 1st is chunkAwait. 

![image](https://user-images.githubusercontent.com/26165117/81747779-9abd5900-94a0-11ea-9ace-87b09083a29f.png)

I _think_ that the majority (if not all) of the [PlayerJoinEvent listener](https://github.com/AddstarMC/Prism-Bukkit/blob/a9fc716154591cac53ad73ce1688c1b709c35ceb/src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java#L115) could _probably_ be run asynchronously since, from what I can tell, it doesn't directly interact with the Bukkit API and is simply for caching. 

Would alleviate a bit (or a lot) of the impact placed upon servers during joining. Mostly beneficial for those that have a lot of people leaving/joining in short periods of time.

**Comment by viveleroi** [comment]
I believe my original intent was to ensure the join was logged/player data was cached so that future logging could contain their data correctly. I'm not sure if that was truly necessary.
