### ISSUE TITLE
[FEATURE] Fix permission prism.parameters.action.required

### ISSUE THREAD

**Issue by Bobcat00** [AddstarMC/Prism-Bukkit#184]
From an admin standpoint, Prism works well if the admin has all permissions, _except_ for the permission `prism.parameters.action.required`.  In this case, having the permission _prevents_ the admin from doing something.  So I'd like to discuss what, if anything, should be done about this.  Some possibilities:

1. Get rid of the permission entirely, making actions optional for everyone.

2. Change the permission to `prism.parameters.action.notrequired`, so if an admin has all permissions, things will work in an intuitive manner.

3. Come up with a way to support both permissions, with one (notrequired?) overriding the other.

Note that this permission does not really fit in with the rest of the permissions (there's no other action.* permission), and is not shown in the Prism documentation from 2016.

Here's a reference to the source lines where the permission is checked:
https://github.com/AddstarMC/Prism-Bukkit/blob/master/src/main/java/me/botsko/prism/commandlibs/PreprocessArgs.java#L109-L114

**Comment by Narimm** [comment]
I always thought this was wierd....I cant even remember why it was done that way...It was changed @viveleroi might have some insight but I think it was changed during the GPrism days

**Comment by viveleroi** [comment]
My goal from day one was to ensure that *leaving something out* wouldn't equal *affecting more of the server*. We had too many mistakes on the logging plugins we used before prism, just because someone forgot an argument (human error, no command auto-complete). My intention was to force prism to use defaults and make the user override it, confirming they clearly know what the result will be. I don't remember that specific permission, but that was the thinking.

**Comment by Bobcat00** [comment]
Is there really a use case for this permission?

The reason I'm bringing it up is because I've noticed a few people tripping over this.

**Comment by Narimm** [comment]
Agreed it is a tripping point - ie the idea of a negative perm

**Comment by Narimm** [comment]
Perhaps what we should do is set a default.  for the action unless either you have a permission to search all actions OR you specify.

The question is what is the default. ie a:place or a:remove

**Comment by Narimm** [comment]
Hey @Bobcat00 I decided to move the permission to `prism.parameters.action-filter-bypass` I wanted to avoid the gobbling that takes place when people use prism.parameters.action.* as a permission check.  

Other than that hope this would work for you
