### ISSUE TITLE
Prism do not resotre items on armor stands.

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#19]
Prism always shows "skipped" while trying to rollback/restore a armor stand. Tested on Spigot 1.12 and the latest build of Prism-Bukkit (as of Jul 2nd).
Strangely Prism could query items being inserted in / removed from a armor stand correctly. I'm guessing Prism is trying to treat all insert/remove actions as it deal with a solid block, instead an entity. In this case, a armor stand is indeed an entity. So that's why Prism skipped the insert/remove?

**Comment by Narimm** [comment]
Its never supported it ..its a known issue
