### ISSUE TITLE
[BUG] /pr undo doesn't work

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#190]
**Describe the bug**
/pr undo appears to not work. We do a rollback, then /pr undo and it says "no previous action."

**To Reproduce**
Perform a rollback and then use `/pr undo`

**Expected behavior**
The rollback should be "undone"

**Screenshots**
N/A

**Server (please complete the following information):**
  - Prism Version: 2.1.6
  - Server Type: Paper
  - Server Version: 1.15.2 b312

**Additional context**
N/A

**Comment by Narimm** [comment]
This is related to #189

**Comment by Narimm** [comment]
Basically when a rollback is performed it stores the parent action id in the additional data field of the handler - however the method hasExtraData() for the rollback action was returning false.

There is another bug stopping this as well that I am working on :)

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
