### ISSUE TITLE
[BUG] Redstone broken by water flow not recorded

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#202]
**Describe the bug**
Redstone broken by water flow is not recorded. Repeaters, torches, etc logged fine.

**To Reproduce**
Place redstone, dump water. Do `/pr l a:break`

**Expected behavior**
Redstone breaking should be logged.

**Screenshots**

**Server (please complete the following information):**
  - Prism Version: 2.1.6
  - Server Type: Paper
  - Server Version: 1.15.2 b341

**Additional context**
N/A

**Comment by Narimm** [comment]
Yeah its missing from the attachments group thanks for the heads up
