### ISSUE TITLE
[BUG] Entity param not working on lookups

### ISSUE THREAD

**Issue by Bobcat00** [AddstarMC/Prism-Bukkit#206]
**Describe the bug**
Suppose `/pr l r:100 t:10m a:kill` returns bats and iron golems being killed.
Adding `e:bat` or `e:iron_golum` returns no results (either you're missing something or we are).

**To Reproduce**
Try the above or similar lookups for entities being killed.

**Expected behavior**
With the above lookups, adding an entity should return results that are a subset of the original lookup.

**Screenshots**

**Server (please complete the following information):**
  - Prism Version: v2.1.7-SNAPSHOT-163
  - Server Type: Spigot
  - Server Version: git-Spigot-a99063f-be6aaf0 (MC: 1.15.2)

**Additional context**

**Comment by Narimm** [comment]
This was fixed with #207 
I have cherry picked it back onto the 1.15_DEV branch - but at this stage I won't be providing builds to that branch
