### ISSUE TITLE
[FEATURE]Excluding Specific Blocks with !

### ISSUE THREAD

**Issue by RanrMC** [AddstarMC/Prism-Bukkit#210]
There is a feature which allows you to exclude specific players and entities from rollbacks and lookups by placing a "!" in front of their username (ex. p:!Ranr). In some cases it would be useful to be able to do the same for specific blocks. The same can be achieved by rolling back and then restore that particular block type, but this would allow it to be done in one rollback.

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
