### ISSUE TITLE
[BUG] Beacon logging errors

### ISSUE THREAD

**Issue by multirp** [AddstarMC/Prism-Bukkit#220]
**Describe the bug**
When breaking a beacon, logs are inserted into the database for that beacon as well as any beacon it is touching, causing an inflated break count.

**To Reproduce**
- Place down several beacons touching one another.  State of the beacon (active/inactive), surface, or face of the beacon it's placed against do not seem to matter, only that several beacons are touching.
- Break one of the beacons
- Run a lookup on beacon breaks, and compare number broken to number logged as broken

**Expected behavior**
When one beacon is broken one log is inserted into the database under any circumstance.

**Screenshots**
Screenshots are included at https://imgur.com/a/Gzgo0bc

**Server (please complete the following information):**
  - Prism Version: 2.1.8-Snapshot-200
  - Server Type: Spigot
  - Server Version: 1.16.2, Build 122

**Comment by Narimm** [comment]
Thanks for the report strong guess that this is because prism looks for custom containers and assumes they are chests

**Comment by Narimm** [comment]
Fixed in #229
