### ISSUE TITLE
[FEATURE]Java 11 support?

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#221]
**Is your feature request related to a problem? Please describe.**
When I try to compile the plugin with Java 8 it gives me `package javax.xml.bind does not exist`. After a quick search I realized that `javax.xml.bind` is dropped from Java 11.

A lot of plugins nowaday support Java 11. Also JRE 11 usually yield better performance with new GCs. We want to move our server into Java 11 and maybe save some ram overhead as well.

**Describe the solution you'd like**
Migrate codes that are still using Java-8-only features.

**Describe alternatives you've considered**
I added a new `dependency` section in the pom.xml according to [this post](https://stackoverflow.com/questions/52502208/). It complies, but not sure how it performed in a jre-11 server. I will post my test run here if I get time to test it.

**Comment by k-jiang** [comment]
Nvm I checked out on the wrong branch :P
My bad sry.

**Comment by k-jiang** [comment]
p.s. The [Jenkins server](https://jenkins.addstar.com.au/job/Prism-Bukkit/changes) seems down, new changes are not build since September 2nd.

**Comment by Narimm** [comment]
The jenkins builds are triggered by me when I want a build out for testing..
