### ISSUE TITLE
Reimplementation of Strikethrough logs for logs that have been rolled back

### ISSUE THREAD

**Issue by ghost** [AddstarMC/Prism-Bukkit#224]
**Is your feature request related to a problem? Please describe.**
Previously there was a feature where if staff rolled back any events, then those logs would be displayed with &n in front of them, striking through the log to indicate that they've been fixed. Then anything not rolled back or restored will not have the strikethrough format. As it is right now, it's extra work for staff (especially on a server with hundreds of players and 2 dozen+ daily tickets) to spend an extra 10 minutes determining not only what happened at a scene, but also if there are logs from other staff members and then exactly what happened/resulted from that staff member, and what's left untouched. This produces double work, and sometimes the possibility of duplicated roll backs of items/events.

**Solution**
- When a player rolls back a log, it would be exactly as it is now, except all logs that are considered "rolled back" will have a strike through them.
- When a player restores a rolled back log, it will do exactly the opposite and simply return it to the beginning state without a strike through it.

**Implementation**
Possibly could be done via a "rolled back" state? for logs, and "if rolled back" then preface the output with "&n" minecraft format code

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
