### ISSUE TITLE
[BUG] Rollback contents of a Shulker Box when exploded.

### ISSUE THREAD

**Issue by Zefferis** [AddstarMC/Prism-Bukkit#228]
**Describe the bug**
When rolling back a shulker chest, the contents of the chest are not restored

**To Reproduce**
In our instance, a creeper exploded a shulker chest containing colored concretes; once rolled back the shulker chest appeared, but not the previous contents.

**Expected behavior**
Contents of a shulker chest should roll back alongside the shulker chest itself.

**Server (please complete the following information):**
  - Prism Version: 2.1.8-Snapshot-201
  - Server Type: Paper
  - Server Version: 1.13.3-b218

**Additional context**
Within vanilla it is "working as intended" that items contained within a shulker box are not dropped when the shulker box is exploded, but I don't feel that should be vanilla-ized for a rollback plugin like Prism:

https://bugs.mojang.com/browse/MC-112781

**Comment by Narimm** [comment]
I believe this should be corrected in build https://jenkins.addstar.com.au/job/Prism-Bukkit/207/
