### ISSUE TITLE
[FEATURE] Add proper command autofill 

### ISSUE THREAD

**Issue by Southpaw1496** [AddstarMC/Prism-Bukkit#233]
**Is your feature request related to a problem? Please describe.**
When performing a lookup or other complex command, it can be frustrating and slightly confusing to not have the syntax properly auto-fill as you type.

**Describe the solution you'd like**
A proper implementation of the commands autocomplete system
**Describe alternatives you've considered**
Well I haven't...

**Additional context**
If anything more would be useful please say so.

**Comment by Narimm** [comment]
Given you have not really outlined what appears to be mssing or described what versions you are referring too ...closed
