### ISSUE TITLE
[BUG] pastegg issues

### ISSUE THREAD

**Issue by PhanaticD** [AddstarMC/Prism-Bukkit#252]
clicking the link the prism plugin gives you is not properly clickable, here is a recording showing the difference between clicking in chat vs clicking the link from plugin message: https://gyazo.com/12e4ac416797515a47bc49689495f6f4

actual pastes do not include locations but rather just say \<location\> here is a picture: https://gyazo.com/d0605cc956840e2bfbbf98a4482718a0

and finally this is more of a feature request, but the paste expiration is not configurable

**Comment by addstar** [comment]
It would really help to know which build/version you are using. I did a little digging and I believe you are running a dev build, newer than the latest release? It seems to be a bug in the current dev builds, but not in the latest released version (2.1.7) on SpigotMC.

Comparison between release/dev code:
- See [this code](https://github.com/AddstarMC/Prism-Bukkit/blob/2.1.7/src/main/java/me/botsko/prism/utils/MiscUtils.java#L141) from released version (working)
- See [this code](https://github.com/AddstarMC/Prism-Bukkit/blob/master/Prism/src/main/java/me/botsko/prism/utils/MiscUtils.java#L144) from master/dev (broken)

Regardless it is a bug, and needs to be fixed.. but just wanted to note that I'm not sure you should be running the latest dev build on live server unless you are just testing it. The current builds are mostly untested by us (we still only run the 2.1.7 branch on our servers).

**Comment by PhanaticD** [comment]
yea I downloaded it off the build server

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
