### ISSUE TITLE
The explosion of the Respawn_anchor will not be recorded

### ISSUE THREAD

**Issue by Crysta11ize** [AddstarMC/Prism-Bukkit#253]
**Describe the bug**
The explosion of the Respawn_anchor will not be recorded

**To Reproduce**
Charge theRespawn_anchor to an explosion in the main world

**Expected behavior**
The explosion should be recorded

**Screenshots**
![QQ图片20210310011252](https://user-images.githubusercontent.com/71912346/110556004-f9457900-813d-11eb-8e4a-f8ec2a4938e6.png)

**Server (please complete the following information):**
  - Prism Version: Prism 2.1.8 b213
  - Server Type: Tuinity
  - Server Version: 1.16.5

**Comment by Narimm** [comment]
Please let me know the exact version of prism your using

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
