### ISSUE TITLE
[FEATURE] Extended command syntax

### ISSUE THREAD

**Issue by multirp** [AddstarMC/Prism-Bukkit#256]
**Is your feature request related to a problem? Please describe.**
Some members seem to have issues with the shortened parameters within a prism command, preferring the longer parameter names found in something like Core Protect.

**Describe the solution you'd like**
Expanding of the parameters of a prism command, with a command looking similar to:
`/prism lookup player:multirp action:break block:stone radius:10 time:1d`

This would be in addition to the normal parameter names that exist now, allowing users to use either the full or shortened version of the parameter in their command usage (ie: time: or t:)

**Additional context**
This may also assist in the training of new members in Prism usage, allowing them to more easily memorize the various parts of the command.

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
