### ISSUE TITLE
[BUG]  Connection error ResultSet.TYPE_FORWARD_ONLY

### ISSUE THREAD

**Issue by Bloodlex** [AddstarMC/Prism-Bukkit#257]
**Describe the bug**
Prism doesn't save any data. It created tables but if I inspect something it says nothing has changed.

Exception pastebin:
[https://pastebin.com/Cb3xnLGH](https://pastebin.com/Cb3xnLGH)

**To Reproduce**
1. Setup MariaDB database.
2. Provide credentials in config.
3. Run the server
4. Get the exception at startup and everytime when inspecting is on

**Expected behavior**
No exception and should save changed data.

**Server (please complete the following information):**
  - Prism Version: 2.1.7
  - Server Type: Paper
  - Server Version: This server is running Paper version git-Paper-550 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Narimm** [comment]
First this is not a bug with Prism per say - 

Another plugin is shading in the MYSQL 8 drivers - which are not backward compatible with MYSQL 5 - they have a much stricter rule set, that plugin should learn how to avoid registering itself the to automated mysql driver pool if it requires that driver.

You can work around this issue by using a Hikari configuration in Prism.
```
#Prism Hikari Datasource Properties for advanced database Configuration
#Sat Jan 02 21:47:38 AEST 2021
initializationFailTimeout=10
validationTimeout=5000
readOnly=false
registerMbeans=false
isolateInternalQueries=false
maxLifetime=1800000
leakDetectionThreshold=0
minimumIdle=1
allowPoolSuspension=false
idleTimeout=600000
dataSourceClassName=com.mysql.jdbc.Driver
dataSource.useSSL=false
dataSource.user=prism
dataSource.password=prism
dataSource.port=3306
dataSource.databaseName=prism
dataSource.serverName=localhost
maximumPoolSize=4
autoCommit=true
connectionTimeout=30000
poolName=prism
#username=prism
#password=prism
```

**Comment by viveleroi** [comment]
Any ideas what plugin might be causing this? Edit: for me it was paper itself, and prism already merged a fix
