### ISSUE TITLE
[BUG] Doesn't support multiple worlds?

### ISSUE THREAD

**Issue by ghost** [AddstarMC/Prism-Bukkit#261]
Only the "world" is recorded, but other worlds are not recorded.

**Comment by NeverGrowUp** [comment]
Unable to reproduce. Please confirm your config.yml has:

>  ignore:
      worlds: []
      worlds_whitelist: false

**Comment by addstar** [comment]
@sourcepowered Sorry but you have not provided enough info for this bug report and you also ignored the issue template so we can't help you. If you are still having problems, feel free to open a new issue but **_please use the template_** and fill in all the details. Thanks!

**Comment by ghost** [comment]
@NeverGrowUp @addstar Yes, my config.yml including the above configuration, but only recording "world" changes. For example, if I want to record the changes of "world_2", what should I do? It is also not stated in the document.
