### ISSUE TITLE
[FEATURE] Mongodb support

### ISSUE THREAD

**Issue by ahdg6** [AddstarMC/Prism-Bukkit#262]
**Is your feature request related to a problem? Please describe.**
It would be awesome to see that the bukkit version of Prism can support Mongodb as it had been implemented in the Sponge version of Prism.

**Describe the solution you'd like**
Add Mongodb support,It will bring performance improve.

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
