### ISSUE TITLE
[FEATURE] Add space after [!] symbol in alert messages

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#265]
I would appreciate seeing the space after the `[!]` symbol in alerts and the message they carry. Or at least a way to provide this via configuration. It was there in the past, but was lost recently.

![javaw_w3kRGN8vtH](https://user-images.githubusercontent.com/70734/119276448-25b25280-bbcf-11eb-9925-d395b21ec99d.png)

**Comment by TNTUP** [comment]
Can confirm this, a bit annoying xD

PS: Is this the real viveleroi? If so, Welcome back!!! been a long user of Prism

**Comment by viveleroi** [comment]
It is, glad you found it helpful! Not sure I'd say I'm back, I've always kinda been around just not usually having to file bugs lol.

**Comment by Rothes** [comment]
https://github.com/AddstarMC/Prism-Bukkit/blob/9ffc93808fb472ac68f87a057188ed2285011257/Prism/src/main/resources/languages/message.properties#L257

**Comment by Rothes** [comment]
https://github.com/AddstarMC/Prism-Bukkit/blob/9ffc93808fb472ac68f87a057188ed2285011257/Prism/src/main/resources/languages/message.properties#L257

**Comment by Narimm** [comment]
Yeah it needs a patch tho @Rothes
