### ISSUE TITLE
Unable to do lookups without specifying an action

### ISSUE THREAD

**Issue by Bobcat00** [AddstarMC/Prism-Bukkit#27]
I'm using CraftBukkit 1.12.2, so I downloaded the repository as of May 30, 2018 and compiled it.  It's working OK, except it's not letting me do lookups without specifying an action.  I recall that with Prism version 2.0.5-14 (for Bukkit 1.8.8), I could do **/pr l r:global t:12h p:Bobcat00**.  But now if I do that, I get the error "You're missing valid actions. Use /prism ? for assistance."

Is this a new restriction or was it changed inadvertently or for some other reason?  Is there a way to allow the lookups without actions again?  (I guess it must be possible somehow, because /pr near looks for all actions.)

And thanks for maintaining this great plugin!

**Comment by Bobcat00** [comment]
Turned out the problem was I gave myself the '*' permission, which includes prism.parameters.action.required

**Comment by alchemistmatt** [comment]
Good find, I figured it was permission related, but I hadn't yet dug into the details.  
Looking now, key permissions that we grant are:
```
prism.help
prism.lookup
prism.lookup.paginate
```

In certain places, we allow
```
prism.parameters.radius
prism.parameters.action
```

And for trusted users we also grant
```
prism.parameters.flag.*
prism.parameters.*
prism.tp
prism.override-max-lookup-radius
```
