### ISSUE TITLE
[FEATURE] Playername searching/Floodgate compatibility

### ISSUE THREAD

**Issue by multirp** [AddstarMC/Prism-Bukkit#277]
**Is your feature request related to a problem? Please describe.**
Bedrock players cannot be effectively searched or rolled back via prism commands when attempting to limit results to the user concerned.

It can track, and roll back, Bedrock players as expected, but only if the search/rollback does not use the player parameter.  If the player parameter is used, the following error message is displayed:
`Unrecognized parameter '~multirp'.  Use /prism ? for help`

**Describe the solution you'd like**
To be able to utilize player-restricted Prism searches and rollbacks regardless of whether the player is Java or Bedrock edition.

While Floodgate allows for no prefix, ideally this solution would work regardless of the prefix chosen by the server.  Even if the formatting is a little weird, like having to use `p:"playername"` or similar.

**Additional context**
This request utilizes Floodgate and Geyser for Bedrock compatibility.  How it works, essentially, is that Bedrock players are able to connect to your server and are given a server-configured prefix to their in-game name (see screenshot).

It is this prefix that interferes with Prism player searches.
![example-login](https://user-images.githubusercontent.com/17681214/127736566-c5ca0765-b26b-49e9-a392-cdb54aad94fa.png)

**Comment by Rothes** [comment]
'~' is used for PARTIAL Match. So the way to solve it may be to add quotes...

**Comment by multirp** [comment]
I had completely forgotten about the partial matching search, if I'm being honest, I do not typically use it.

This is an issue with all non-alphanumeric characters though.  From my testing, ".multirp" (which we had originally, caused issues with permissions), "~multirp", "#multirp", and "&multirp" all do not work.  "_multirp" does work, but an underscore is a valid minecraft name character.

Quotes would, honestly, be fine with me.  I could not see this as a 'major' issue.  Sort of requires Floodgate, then requires those bedrock players to do something requiring a rollback and even then most actions can be performed fine utilizing the commands in place ("!player" to ignore another player in the area, a carefully constructed non-player rollback, etc)

**Comment by Rothes** [comment]
In Regex it only detect characters in players' name range "A-Z a-z 0-9" or "_". Any other characters are invalid now.
This should be changed if we support Unicodes.

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
