### ISSUE TITLE
[FEATURE] Add a symbol for records that has been rollbacked.

### ISSUE THREAD

**Issue by Rothes** [AddstarMC/Prism-Bukkit#280]
**Describe the solution you'd like**
After processing a lookup, Prism will show us the result. The records which have been rollbacked show as normal, we may change this to reduce clutter.

**Describe alternatives you've considered**
Maybe just add a STRIKETHROUGH decorate for those rollbacked, like other plugins.

**Additional context**
This may involve some api and database changes...

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
