### ISSUE TITLE
[BUG] Update Deprecations - String to Components

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#283]
**Describe the bug**
With adventure now itegrated  - a large number of displayable text fields have been deprecated and renamed - these are fields that support colors and formating that cannot be clearly displayed in regular strings - 

These will need updating - however it will not be compatible with Spigot 

Currently we lose data if an item/block / book has things like clickable links /commands and is destroyed but then rollback occurs.  The custom data is lost - this would fix that.

**Server (please complete the following information):**
  - Prism Version: 2.1.8-SNAPSHOT
  - Server Type: Paper
  - Server Version: 1.17

**Comment by Rothes** [comment]
Can we use Spigot ChatComponent since advanture has been itegrated from 1.17?
It doesnt support replaceText though

**Comment by Bobcat00** [comment]
"it will not be compatible with Spigot" ???

**Comment by Rothes** [comment]
> "it will not be compatible with Spigot" ???

advanture components is integrated in PaperSpigot.
Spigot doesn't contain this api so plugin will not work on Spigot any more.

If we still need to use advanture, but support Spigot at the same time, can we use relocate in maven?

**Comment by Bobcat00** [comment]
Not supporting Spigot would be a stupid thing to do, and of course your plugin will be removed from the Spigot web site.

**Comment by Narimm** [comment]
> > "it will not be compatible with Spigot" ???
> 
> advanture components is integrated in PaperSpigot.
> Spigot doesn't contain this api so plugin will not work on Spigot any more.
> 
> If we still need to use advanture, but support Spigot at the same time, can we use relocate in maven?
Yes and No -

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
