### ISSUE TITLE
[BUG] Prism does not store extra ItemStack data (PDC/NBT)

### ISSUE THREAD

**Issue by Cryptite** [AddstarMC/Prism-Bukkit#287]
**Describe the bug**
If any item logged by prism has extra data in the form of things like NBT Tags, it will not save them and/or will not restore them when trying to do a rollback.

Short and sweet!

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
