### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by vacla** [AddstarMC/Prism-Bukkit#290]
**Describe the bug**
Replace the placeholder with blockname, currently it uses the wrong placeholder.

**To Reproduce**
Use the prism inspector

**Expected behavior**
<blockname> would say a blockname

**Server (please complete the following information):**
prism github, master branch

**Additional context**
https://github.com/AddstarMC/Prism-Bukkit/blob/26bec8d35025b43eaea90d81abb3c24338683ab4/Prism/src/main/java/me/botsko/prism/wands/InspectorWand.java#L91-L97
https://github.com/AddstarMC/Prism-Bukkit/blob/26bec8d35025b43eaea90d81abb3c24338683ab4/Prism/src/main/resources/languages/message.properties#L145

**Comment by Rothes** [comment]
This is already fixed in https://github.com/AddstarMC/Prism-Bukkit/pull/274
Just waiting for the merge.

**Comment by vacla** [comment]
Ah ok, noticed it with updating Watson, updating the "message formats" atm
