### ISSUE TITLE
[BUG] Properly register command permissions

### ISSUE THREAD

**Issue by Artuto** [AddstarMC/Prism-Bukkit#298]
**Describe the bug**
Currently, all commands are sent to the client regardless or not they have permission to use it. While this is a minor issue, it does not make sense for players to have commands in their command menu that they cannot use.

**To Reproduce**
1. Install Prism
2. Check the tab complete

**Expected behavior**
Prism should properly set command's permissions.

![image](https://user-images.githubusercontent.com/9273973/151681802-29207c3b-63ae-4633-b19f-bc1c61c0dada.png)

Notice how Bukkit does not know of this command's permission (because Prism is doing it's own check).

**Screenshots**
![image](https://user-images.githubusercontent.com/9273973/151681695-6aa324b7-3fb8-4827-80cf-351115b13ab5.png)

**Server (please complete the following information):**
  - Prism Version: 2.2.0-SNAPSHOT
  - Server Type: Paper
  - Server Version: 1.18.1

**Additional context**
n/a

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
