### ISSUE TITLE
Feature request: pre/next page buttons, click to tp, and details display

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#32]
First I would like to thank all who continually contribute to the Prism-Bukkit project. You all are doing great jobs on this!

I was using Prism-Bukkit for 1.12.2 and it was able to click on the inspection records and be teleported to the location directly. And the prev/next page buttons was so convenient. Hover on the records also shows detailed informations as well.

However since https://github.com/AddstarMC/Prism-Bukkit/commit/4fc8337dd15a66e8c67c2238450f868956ce8f06#diff-c09f0bc40dbe87b7512f4ffdb77a8840 , those functions are lost due to merging. Can I have those functionalities back in 1.13 please?

Thank you again for your contribution!

**Comment by Narimm** [comment]
Yeah chat changed dramatically in 1.13 so it might be a while on this one!

**Comment by Narimm** [comment]
Should be fixed in the latest master for 1.14
