### ISSUE TITLE
Missing Database name configuration

### ISSUE THREAD

**Issue by lifehome** [AddstarMC/Prism-Bukkit#33]
https://github.com/AddstarMC/Prism-Bukkit/blob/4f551453f4632c9b562777d1e2a775d1237fc471/src/main/java/me/botsko/prism/database/mysql/MySQLPrismDataSource.java#L25

https://github.com/AddstarMC/Prism-Bukkit/blob/4f551453f4632c9b562777d1e2a775d1237fc471/src/main/java/me/botsko/prism/PrismConfig.java#L43-L52

Actually the "database" node gets overriden by appending childs onto it, so that the option vanished completely. However I noticed that the DataSource file have another option for that, perhaps it should be inside the default config?

**Comment by Narimm** [comment]
Oh of course it does I will fix that - are you runnig this branch - I havent even locally started testing this abstraction

**Comment by lifehome** [comment]
LOL actually I checked this branch out mistakenly. Been compiled it once, filled the config and spin it up, tho it keeps using default values instead of configured ones, no idea why.

I'm now back to 2.1.0 on master branch tho :3

**Comment by PhanaticD** [comment]
yea after this commit seems like the config gets default written every startup

**Comment by Narimm** [comment]
Thanks I actually havent tested this yet ...so please test it if you like but dont use it in production

**Comment by Narimm** [comment]
Sorted and merged into MASTER
