### ISSUE TITLE
Prism 1.8.3

### ISSUE THREAD

**Issue by kangarko** [AddstarMC/Prism-Bukkit#4]
Since the GSON library has changed imports, plugin breaks.

**Comment by kangarko** [comment]
Opened a pull request :)

**Comment by addstar** [comment]
You did? I don't see a pull request.. this is an issue not a PR.
I will be working on the 1.8.3 stuff soon but we're not running it yet on our server so it's not urgent for us.

**Comment by kangarko** [comment]
https://github.com/addstar/Prism-Bukkit/pull/5

**Comment by SonarBeserk** [comment]
Note these changes have been added to the official upstream version.
