### ISSUE TITLE
Feature request: Log damages done with Magic (Hook with Magic Plugin)

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#46]
Can Prism log block breaked / entity killed with Magic? Here is a link to the Magic Plugin:
https://github.com/elBukkit/MagicPlugin

Magic is a popular RPG plugins that allow custom Magic effects.

Thank You!

**Comment by addstar** [comment]
Unfortunately we don't use this plugin and this kind of integrations will probably take a lot of work/time. Sadly we don't have time to work on things like this, especially since we don't use the Magic plugin.

But we welcome PRs for changes if someone is interested in making the changes :)
