### ISSUE TITLE
Clicking on signs throws console error while /pr i'ing

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Prism-Bukkit#60]
https://pastebin.com/Nw3Bidz9

Steps to reproduce:
Place a sign. Either have text or not. 
DO /pr i then left/right click on the sign
????
Console error, not profit!

Though Prism logs the sign content as usual, clicking on them throws a stacktrace

**Comment by addstar** [comment]
Thanks for the report, we have also confirmed this happening and we'll get it fixed up :+1:

**Comment by TNTUP** [comment]
No problem! Glad I can help and I'm very happy to use Prism back! <3

**Comment by addstar** [comment]
Also, unrelated but I've just pushed a new build which should fix bStats metrics. It would be great if you wouldn't mind trying that so we can get some others testing the change?

https://jenkins.addstar.com.au/job/Prism-Bukkit/75/

**Comment by TNTUP** [comment]
> Also, unrelated but I've just pushed a new build which should fix bStats metrics. It would be great if you wouldn't mind trying that so we can get some others testing the change?
> 
> https://jenkins.addstar.com.au/job/Prism-Bukkit/75/

Will do, can't seem to download but is the "module" the actual plugin jar file? I've found a way to peek in your artifactory and downloaded it there.

**Comment by addstar** [comment]
> can't seem to download but is the "module" the actual plugin jar file

huh.. you're right, it's not meant to be like that.. but yes the module jar is the one to download :) Glad it's working for you! I can see the metrics on bStats!

**Comment by TNTUP** [comment]
> > can't seem to download but is the "module" the actual plugin jar file
> 
> huh.. you're right, it's not meant to be like that.. but yes the module jar is the one to download :) Glad it's working for you! I can see the metrics on bStats!

Nice!! Glad the bStats works, will leave it enabled to keep awesome stats!

Will remember next time where to dl it!

**Comment by addstar** [comment]
I've found the cause of this issue. Prism is attempting to access world data on an async thread.. that's a very big no no.. so long ago they implemented a fail-safe to stop this kind of code and prevent data corruption.

So I'm working on restructuring the code to work in more safe ways... stay tuned..

**Comment by addstar** [comment]
@TNTUP All fixed :)

https://jenkins.addstar.com.au/job/Prism-Bukkit/76/

**Comment by TNTUP** [comment]
Fast fix! Thanks!

**Comment by Bobcat00** [comment]
I click on the build number, then "Module Builds", and that gets me download links for the jar file.
