### ISSUE TITLE
negative itemstacks

### ISSUE THREAD

**Issue by PhanaticD** [AddstarMC/Prism-Bukkit#7]
http://gyazo.com/88c54c5b00b2c557f07165de5ecd1b22

**Comment by addstar** [comment]
Can you provide more info? Which build was this with?
What steps did you perform to make this happen?

**Comment by PhanaticD** [comment]
it was with build 9 and I just did a regular rollback

**Comment by addstar** [comment]
It would be near impossible to track down what exactly happened without more info.
I'll just have to put in a limiter to prevent negative itemstack amounts.

**Comment by PhanaticD** [comment]
I did /pr rs r:we t:90d to restore a chest a mod accidentally deleted and ended up with this: http://gyazo.com/ed39fdf9ae7e9858834d80965d0f329b

using build 12

**Comment by addstar** [comment]
So the chest contained these items? Did the mod broke the chest normally with a tool or hand? Did they pickup the dropped items? Are you able to reproduce this issue?

**Comment by PhanaticD** [comment]
still happening I have been trying to find a way to reproduce it but I cant it just happens sometimes
